// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: item.proto

package dk.via.nbnp.databaseserver.protobuf;

public interface GetItemCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetItemCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 count = 1;</code>
   * @return The count.
   */
  long getCount();
}
