// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package dk.via.nbnp.databaseserver.protobuf;

public interface SearchProductDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchProductDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
