// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conversation.proto

package dk.via.nbnp.databaseserver.protobuf;

/**
 * Protobuf type {@code Conversation}
 */
public final class Conversation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Conversation)
    ConversationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Conversation.newBuilder() to construct.
  private Conversation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Conversation() {
    messages_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Conversation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Conversation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            dk.via.nbnp.databaseserver.protobuf.User.Builder subBuilder = null;
            if (seller_ != null) {
              subBuilder = seller_.toBuilder();
            }
            seller_ = input.readMessage(dk.via.nbnp.databaseserver.protobuf.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(seller_);
              seller_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            dk.via.nbnp.databaseserver.protobuf.User.Builder subBuilder = null;
            if (buyer_ != null) {
              subBuilder = buyer_.toBuilder();
            }
            buyer_ = input.readMessage(dk.via.nbnp.databaseserver.protobuf.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(buyer_);
              buyer_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            dk.via.nbnp.databaseserver.protobuf.Item.Builder subBuilder = null;
            if (item_ != null) {
              subBuilder = item_.toBuilder();
            }
            item_ = input.readMessage(dk.via.nbnp.databaseserver.protobuf.Item.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(item_);
              item_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder subBuilder = null;
            if (dateOfStart_ != null) {
              subBuilder = dateOfStart_.toBuilder();
            }
            dateOfStart_ = input.readMessage(dk.via.nbnp.databaseserver.protobuf.LocalDateTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateOfStart_);
              dateOfStart_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              messages_ = new java.util.ArrayList<dk.via.nbnp.databaseserver.protobuf.Message>();
              mutable_bitField0_ |= 0x00000001;
            }
            messages_.add(
                input.readMessage(dk.via.nbnp.databaseserver.protobuf.Message.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        messages_ = java.util.Collections.unmodifiableList(messages_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.nbnp.databaseserver.protobuf.ConversationOuterClass.internal_static_Conversation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.nbnp.databaseserver.protobuf.ConversationOuterClass.internal_static_Conversation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.nbnp.databaseserver.protobuf.Conversation.class, dk.via.nbnp.databaseserver.protobuf.Conversation.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int SELLER_FIELD_NUMBER = 2;
  private dk.via.nbnp.databaseserver.protobuf.User seller_;
  /**
   * <code>.User seller = 2;</code>
   * @return Whether the seller field is set.
   */
  @java.lang.Override
  public boolean hasSeller() {
    return seller_ != null;
  }
  /**
   * <code>.User seller = 2;</code>
   * @return The seller.
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.User getSeller() {
    return seller_ == null ? dk.via.nbnp.databaseserver.protobuf.User.getDefaultInstance() : seller_;
  }
  /**
   * <code>.User seller = 2;</code>
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.UserOrBuilder getSellerOrBuilder() {
    return getSeller();
  }

  public static final int BUYER_FIELD_NUMBER = 3;
  private dk.via.nbnp.databaseserver.protobuf.User buyer_;
  /**
   * <code>.User buyer = 3;</code>
   * @return Whether the buyer field is set.
   */
  @java.lang.Override
  public boolean hasBuyer() {
    return buyer_ != null;
  }
  /**
   * <code>.User buyer = 3;</code>
   * @return The buyer.
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.User getBuyer() {
    return buyer_ == null ? dk.via.nbnp.databaseserver.protobuf.User.getDefaultInstance() : buyer_;
  }
  /**
   * <code>.User buyer = 3;</code>
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.UserOrBuilder getBuyerOrBuilder() {
    return getBuyer();
  }

  public static final int ITEM_FIELD_NUMBER = 4;
  private dk.via.nbnp.databaseserver.protobuf.Item item_;
  /**
   * <code>.Item item = 4;</code>
   * @return Whether the item field is set.
   */
  @java.lang.Override
  public boolean hasItem() {
    return item_ != null;
  }
  /**
   * <code>.Item item = 4;</code>
   * @return The item.
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.Item getItem() {
    return item_ == null ? dk.via.nbnp.databaseserver.protobuf.Item.getDefaultInstance() : item_;
  }
  /**
   * <code>.Item item = 4;</code>
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.ItemOrBuilder getItemOrBuilder() {
    return getItem();
  }

  public static final int DATEOFSTART_FIELD_NUMBER = 5;
  private dk.via.nbnp.databaseserver.protobuf.LocalDateTime dateOfStart_;
  /**
   * <code>.LocalDateTime dateOfStart = 5;</code>
   * @return Whether the dateOfStart field is set.
   */
  @java.lang.Override
  public boolean hasDateOfStart() {
    return dateOfStart_ != null;
  }
  /**
   * <code>.LocalDateTime dateOfStart = 5;</code>
   * @return The dateOfStart.
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.LocalDateTime getDateOfStart() {
    return dateOfStart_ == null ? dk.via.nbnp.databaseserver.protobuf.LocalDateTime.getDefaultInstance() : dateOfStart_;
  }
  /**
   * <code>.LocalDateTime dateOfStart = 5;</code>
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.LocalDateTimeOrBuilder getDateOfStartOrBuilder() {
    return getDateOfStart();
  }

  public static final int MESSAGES_FIELD_NUMBER = 6;
  private java.util.List<dk.via.nbnp.databaseserver.protobuf.Message> messages_;
  /**
   * <code>repeated .Message messages = 6;</code>
   */
  @java.lang.Override
  public java.util.List<dk.via.nbnp.databaseserver.protobuf.Message> getMessagesList() {
    return messages_;
  }
  /**
   * <code>repeated .Message messages = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dk.via.nbnp.databaseserver.protobuf.MessageOrBuilder> 
      getMessagesOrBuilderList() {
    return messages_;
  }
  /**
   * <code>repeated .Message messages = 6;</code>
   */
  @java.lang.Override
  public int getMessagesCount() {
    return messages_.size();
  }
  /**
   * <code>repeated .Message messages = 6;</code>
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.Message getMessages(int index) {
    return messages_.get(index);
  }
  /**
   * <code>repeated .Message messages = 6;</code>
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.MessageOrBuilder getMessagesOrBuilder(
      int index) {
    return messages_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (seller_ != null) {
      output.writeMessage(2, getSeller());
    }
    if (buyer_ != null) {
      output.writeMessage(3, getBuyer());
    }
    if (item_ != null) {
      output.writeMessage(4, getItem());
    }
    if (dateOfStart_ != null) {
      output.writeMessage(5, getDateOfStart());
    }
    for (int i = 0; i < messages_.size(); i++) {
      output.writeMessage(6, messages_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (seller_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSeller());
    }
    if (buyer_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBuyer());
    }
    if (item_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getItem());
    }
    if (dateOfStart_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDateOfStart());
    }
    for (int i = 0; i < messages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, messages_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.nbnp.databaseserver.protobuf.Conversation)) {
      return super.equals(obj);
    }
    dk.via.nbnp.databaseserver.protobuf.Conversation other = (dk.via.nbnp.databaseserver.protobuf.Conversation) obj;

    if (getId()
        != other.getId()) return false;
    if (hasSeller() != other.hasSeller()) return false;
    if (hasSeller()) {
      if (!getSeller()
          .equals(other.getSeller())) return false;
    }
    if (hasBuyer() != other.hasBuyer()) return false;
    if (hasBuyer()) {
      if (!getBuyer()
          .equals(other.getBuyer())) return false;
    }
    if (hasItem() != other.hasItem()) return false;
    if (hasItem()) {
      if (!getItem()
          .equals(other.getItem())) return false;
    }
    if (hasDateOfStart() != other.hasDateOfStart()) return false;
    if (hasDateOfStart()) {
      if (!getDateOfStart()
          .equals(other.getDateOfStart())) return false;
    }
    if (!getMessagesList()
        .equals(other.getMessagesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasSeller()) {
      hash = (37 * hash) + SELLER_FIELD_NUMBER;
      hash = (53 * hash) + getSeller().hashCode();
    }
    if (hasBuyer()) {
      hash = (37 * hash) + BUYER_FIELD_NUMBER;
      hash = (53 * hash) + getBuyer().hashCode();
    }
    if (hasItem()) {
      hash = (37 * hash) + ITEM_FIELD_NUMBER;
      hash = (53 * hash) + getItem().hashCode();
    }
    if (hasDateOfStart()) {
      hash = (37 * hash) + DATEOFSTART_FIELD_NUMBER;
      hash = (53 * hash) + getDateOfStart().hashCode();
    }
    if (getMessagesCount() > 0) {
      hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getMessagesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Conversation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.nbnp.databaseserver.protobuf.Conversation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Conversation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Conversation)
      dk.via.nbnp.databaseserver.protobuf.ConversationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.nbnp.databaseserver.protobuf.ConversationOuterClass.internal_static_Conversation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.nbnp.databaseserver.protobuf.ConversationOuterClass.internal_static_Conversation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.nbnp.databaseserver.protobuf.Conversation.class, dk.via.nbnp.databaseserver.protobuf.Conversation.Builder.class);
    }

    // Construct using dk.via.nbnp.databaseserver.protobuf.Conversation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMessagesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      if (sellerBuilder_ == null) {
        seller_ = null;
      } else {
        seller_ = null;
        sellerBuilder_ = null;
      }
      if (buyerBuilder_ == null) {
        buyer_ = null;
      } else {
        buyer_ = null;
        buyerBuilder_ = null;
      }
      if (itemBuilder_ == null) {
        item_ = null;
      } else {
        item_ = null;
        itemBuilder_ = null;
      }
      if (dateOfStartBuilder_ == null) {
        dateOfStart_ = null;
      } else {
        dateOfStart_ = null;
        dateOfStartBuilder_ = null;
      }
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        messagesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.nbnp.databaseserver.protobuf.ConversationOuterClass.internal_static_Conversation_descriptor;
    }

    @java.lang.Override
    public dk.via.nbnp.databaseserver.protobuf.Conversation getDefaultInstanceForType() {
      return dk.via.nbnp.databaseserver.protobuf.Conversation.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.nbnp.databaseserver.protobuf.Conversation build() {
      dk.via.nbnp.databaseserver.protobuf.Conversation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.nbnp.databaseserver.protobuf.Conversation buildPartial() {
      dk.via.nbnp.databaseserver.protobuf.Conversation result = new dk.via.nbnp.databaseserver.protobuf.Conversation(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (sellerBuilder_ == null) {
        result.seller_ = seller_;
      } else {
        result.seller_ = sellerBuilder_.build();
      }
      if (buyerBuilder_ == null) {
        result.buyer_ = buyer_;
      } else {
        result.buyer_ = buyerBuilder_.build();
      }
      if (itemBuilder_ == null) {
        result.item_ = item_;
      } else {
        result.item_ = itemBuilder_.build();
      }
      if (dateOfStartBuilder_ == null) {
        result.dateOfStart_ = dateOfStart_;
      } else {
        result.dateOfStart_ = dateOfStartBuilder_.build();
      }
      if (messagesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.messages_ = messages_;
      } else {
        result.messages_ = messagesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.nbnp.databaseserver.protobuf.Conversation) {
        return mergeFrom((dk.via.nbnp.databaseserver.protobuf.Conversation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.nbnp.databaseserver.protobuf.Conversation other) {
      if (other == dk.via.nbnp.databaseserver.protobuf.Conversation.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasSeller()) {
        mergeSeller(other.getSeller());
      }
      if (other.hasBuyer()) {
        mergeBuyer(other.getBuyer());
      }
      if (other.hasItem()) {
        mergeItem(other.getItem());
      }
      if (other.hasDateOfStart()) {
        mergeDateOfStart(other.getDateOfStart());
      }
      if (messagesBuilder_ == null) {
        if (!other.messages_.isEmpty()) {
          if (messages_.isEmpty()) {
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessagesIsMutable();
            messages_.addAll(other.messages_);
          }
          onChanged();
        }
      } else {
        if (!other.messages_.isEmpty()) {
          if (messagesBuilder_.isEmpty()) {
            messagesBuilder_.dispose();
            messagesBuilder_ = null;
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000001);
            messagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMessagesFieldBuilder() : null;
          } else {
            messagesBuilder_.addAllMessages(other.messages_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.nbnp.databaseserver.protobuf.Conversation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.nbnp.databaseserver.protobuf.Conversation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private dk.via.nbnp.databaseserver.protobuf.User seller_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.User, dk.via.nbnp.databaseserver.protobuf.User.Builder, dk.via.nbnp.databaseserver.protobuf.UserOrBuilder> sellerBuilder_;
    /**
     * <code>.User seller = 2;</code>
     * @return Whether the seller field is set.
     */
    public boolean hasSeller() {
      return sellerBuilder_ != null || seller_ != null;
    }
    /**
     * <code>.User seller = 2;</code>
     * @return The seller.
     */
    public dk.via.nbnp.databaseserver.protobuf.User getSeller() {
      if (sellerBuilder_ == null) {
        return seller_ == null ? dk.via.nbnp.databaseserver.protobuf.User.getDefaultInstance() : seller_;
      } else {
        return sellerBuilder_.getMessage();
      }
    }
    /**
     * <code>.User seller = 2;</code>
     */
    public Builder setSeller(dk.via.nbnp.databaseserver.protobuf.User value) {
      if (sellerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        seller_ = value;
        onChanged();
      } else {
        sellerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.User seller = 2;</code>
     */
    public Builder setSeller(
        dk.via.nbnp.databaseserver.protobuf.User.Builder builderForValue) {
      if (sellerBuilder_ == null) {
        seller_ = builderForValue.build();
        onChanged();
      } else {
        sellerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.User seller = 2;</code>
     */
    public Builder mergeSeller(dk.via.nbnp.databaseserver.protobuf.User value) {
      if (sellerBuilder_ == null) {
        if (seller_ != null) {
          seller_ =
            dk.via.nbnp.databaseserver.protobuf.User.newBuilder(seller_).mergeFrom(value).buildPartial();
        } else {
          seller_ = value;
        }
        onChanged();
      } else {
        sellerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.User seller = 2;</code>
     */
    public Builder clearSeller() {
      if (sellerBuilder_ == null) {
        seller_ = null;
        onChanged();
      } else {
        seller_ = null;
        sellerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.User seller = 2;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.User.Builder getSellerBuilder() {
      
      onChanged();
      return getSellerFieldBuilder().getBuilder();
    }
    /**
     * <code>.User seller = 2;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.UserOrBuilder getSellerOrBuilder() {
      if (sellerBuilder_ != null) {
        return sellerBuilder_.getMessageOrBuilder();
      } else {
        return seller_ == null ?
            dk.via.nbnp.databaseserver.protobuf.User.getDefaultInstance() : seller_;
      }
    }
    /**
     * <code>.User seller = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.User, dk.via.nbnp.databaseserver.protobuf.User.Builder, dk.via.nbnp.databaseserver.protobuf.UserOrBuilder> 
        getSellerFieldBuilder() {
      if (sellerBuilder_ == null) {
        sellerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.nbnp.databaseserver.protobuf.User, dk.via.nbnp.databaseserver.protobuf.User.Builder, dk.via.nbnp.databaseserver.protobuf.UserOrBuilder>(
                getSeller(),
                getParentForChildren(),
                isClean());
        seller_ = null;
      }
      return sellerBuilder_;
    }

    private dk.via.nbnp.databaseserver.protobuf.User buyer_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.User, dk.via.nbnp.databaseserver.protobuf.User.Builder, dk.via.nbnp.databaseserver.protobuf.UserOrBuilder> buyerBuilder_;
    /**
     * <code>.User buyer = 3;</code>
     * @return Whether the buyer field is set.
     */
    public boolean hasBuyer() {
      return buyerBuilder_ != null || buyer_ != null;
    }
    /**
     * <code>.User buyer = 3;</code>
     * @return The buyer.
     */
    public dk.via.nbnp.databaseserver.protobuf.User getBuyer() {
      if (buyerBuilder_ == null) {
        return buyer_ == null ? dk.via.nbnp.databaseserver.protobuf.User.getDefaultInstance() : buyer_;
      } else {
        return buyerBuilder_.getMessage();
      }
    }
    /**
     * <code>.User buyer = 3;</code>
     */
    public Builder setBuyer(dk.via.nbnp.databaseserver.protobuf.User value) {
      if (buyerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        buyer_ = value;
        onChanged();
      } else {
        buyerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.User buyer = 3;</code>
     */
    public Builder setBuyer(
        dk.via.nbnp.databaseserver.protobuf.User.Builder builderForValue) {
      if (buyerBuilder_ == null) {
        buyer_ = builderForValue.build();
        onChanged();
      } else {
        buyerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.User buyer = 3;</code>
     */
    public Builder mergeBuyer(dk.via.nbnp.databaseserver.protobuf.User value) {
      if (buyerBuilder_ == null) {
        if (buyer_ != null) {
          buyer_ =
            dk.via.nbnp.databaseserver.protobuf.User.newBuilder(buyer_).mergeFrom(value).buildPartial();
        } else {
          buyer_ = value;
        }
        onChanged();
      } else {
        buyerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.User buyer = 3;</code>
     */
    public Builder clearBuyer() {
      if (buyerBuilder_ == null) {
        buyer_ = null;
        onChanged();
      } else {
        buyer_ = null;
        buyerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.User buyer = 3;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.User.Builder getBuyerBuilder() {
      
      onChanged();
      return getBuyerFieldBuilder().getBuilder();
    }
    /**
     * <code>.User buyer = 3;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.UserOrBuilder getBuyerOrBuilder() {
      if (buyerBuilder_ != null) {
        return buyerBuilder_.getMessageOrBuilder();
      } else {
        return buyer_ == null ?
            dk.via.nbnp.databaseserver.protobuf.User.getDefaultInstance() : buyer_;
      }
    }
    /**
     * <code>.User buyer = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.User, dk.via.nbnp.databaseserver.protobuf.User.Builder, dk.via.nbnp.databaseserver.protobuf.UserOrBuilder> 
        getBuyerFieldBuilder() {
      if (buyerBuilder_ == null) {
        buyerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.nbnp.databaseserver.protobuf.User, dk.via.nbnp.databaseserver.protobuf.User.Builder, dk.via.nbnp.databaseserver.protobuf.UserOrBuilder>(
                getBuyer(),
                getParentForChildren(),
                isClean());
        buyer_ = null;
      }
      return buyerBuilder_;
    }

    private dk.via.nbnp.databaseserver.protobuf.Item item_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.Item, dk.via.nbnp.databaseserver.protobuf.Item.Builder, dk.via.nbnp.databaseserver.protobuf.ItemOrBuilder> itemBuilder_;
    /**
     * <code>.Item item = 4;</code>
     * @return Whether the item field is set.
     */
    public boolean hasItem() {
      return itemBuilder_ != null || item_ != null;
    }
    /**
     * <code>.Item item = 4;</code>
     * @return The item.
     */
    public dk.via.nbnp.databaseserver.protobuf.Item getItem() {
      if (itemBuilder_ == null) {
        return item_ == null ? dk.via.nbnp.databaseserver.protobuf.Item.getDefaultInstance() : item_;
      } else {
        return itemBuilder_.getMessage();
      }
    }
    /**
     * <code>.Item item = 4;</code>
     */
    public Builder setItem(dk.via.nbnp.databaseserver.protobuf.Item value) {
      if (itemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        item_ = value;
        onChanged();
      } else {
        itemBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Item item = 4;</code>
     */
    public Builder setItem(
        dk.via.nbnp.databaseserver.protobuf.Item.Builder builderForValue) {
      if (itemBuilder_ == null) {
        item_ = builderForValue.build();
        onChanged();
      } else {
        itemBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Item item = 4;</code>
     */
    public Builder mergeItem(dk.via.nbnp.databaseserver.protobuf.Item value) {
      if (itemBuilder_ == null) {
        if (item_ != null) {
          item_ =
            dk.via.nbnp.databaseserver.protobuf.Item.newBuilder(item_).mergeFrom(value).buildPartial();
        } else {
          item_ = value;
        }
        onChanged();
      } else {
        itemBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Item item = 4;</code>
     */
    public Builder clearItem() {
      if (itemBuilder_ == null) {
        item_ = null;
        onChanged();
      } else {
        item_ = null;
        itemBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Item item = 4;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.Item.Builder getItemBuilder() {
      
      onChanged();
      return getItemFieldBuilder().getBuilder();
    }
    /**
     * <code>.Item item = 4;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.ItemOrBuilder getItemOrBuilder() {
      if (itemBuilder_ != null) {
        return itemBuilder_.getMessageOrBuilder();
      } else {
        return item_ == null ?
            dk.via.nbnp.databaseserver.protobuf.Item.getDefaultInstance() : item_;
      }
    }
    /**
     * <code>.Item item = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.Item, dk.via.nbnp.databaseserver.protobuf.Item.Builder, dk.via.nbnp.databaseserver.protobuf.ItemOrBuilder> 
        getItemFieldBuilder() {
      if (itemBuilder_ == null) {
        itemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.nbnp.databaseserver.protobuf.Item, dk.via.nbnp.databaseserver.protobuf.Item.Builder, dk.via.nbnp.databaseserver.protobuf.ItemOrBuilder>(
                getItem(),
                getParentForChildren(),
                isClean());
        item_ = null;
      }
      return itemBuilder_;
    }

    private dk.via.nbnp.databaseserver.protobuf.LocalDateTime dateOfStart_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.LocalDateTime, dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder, dk.via.nbnp.databaseserver.protobuf.LocalDateTimeOrBuilder> dateOfStartBuilder_;
    /**
     * <code>.LocalDateTime dateOfStart = 5;</code>
     * @return Whether the dateOfStart field is set.
     */
    public boolean hasDateOfStart() {
      return dateOfStartBuilder_ != null || dateOfStart_ != null;
    }
    /**
     * <code>.LocalDateTime dateOfStart = 5;</code>
     * @return The dateOfStart.
     */
    public dk.via.nbnp.databaseserver.protobuf.LocalDateTime getDateOfStart() {
      if (dateOfStartBuilder_ == null) {
        return dateOfStart_ == null ? dk.via.nbnp.databaseserver.protobuf.LocalDateTime.getDefaultInstance() : dateOfStart_;
      } else {
        return dateOfStartBuilder_.getMessage();
      }
    }
    /**
     * <code>.LocalDateTime dateOfStart = 5;</code>
     */
    public Builder setDateOfStart(dk.via.nbnp.databaseserver.protobuf.LocalDateTime value) {
      if (dateOfStartBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateOfStart_ = value;
        onChanged();
      } else {
        dateOfStartBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.LocalDateTime dateOfStart = 5;</code>
     */
    public Builder setDateOfStart(
        dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder builderForValue) {
      if (dateOfStartBuilder_ == null) {
        dateOfStart_ = builderForValue.build();
        onChanged();
      } else {
        dateOfStartBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.LocalDateTime dateOfStart = 5;</code>
     */
    public Builder mergeDateOfStart(dk.via.nbnp.databaseserver.protobuf.LocalDateTime value) {
      if (dateOfStartBuilder_ == null) {
        if (dateOfStart_ != null) {
          dateOfStart_ =
            dk.via.nbnp.databaseserver.protobuf.LocalDateTime.newBuilder(dateOfStart_).mergeFrom(value).buildPartial();
        } else {
          dateOfStart_ = value;
        }
        onChanged();
      } else {
        dateOfStartBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.LocalDateTime dateOfStart = 5;</code>
     */
    public Builder clearDateOfStart() {
      if (dateOfStartBuilder_ == null) {
        dateOfStart_ = null;
        onChanged();
      } else {
        dateOfStart_ = null;
        dateOfStartBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.LocalDateTime dateOfStart = 5;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder getDateOfStartBuilder() {
      
      onChanged();
      return getDateOfStartFieldBuilder().getBuilder();
    }
    /**
     * <code>.LocalDateTime dateOfStart = 5;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.LocalDateTimeOrBuilder getDateOfStartOrBuilder() {
      if (dateOfStartBuilder_ != null) {
        return dateOfStartBuilder_.getMessageOrBuilder();
      } else {
        return dateOfStart_ == null ?
            dk.via.nbnp.databaseserver.protobuf.LocalDateTime.getDefaultInstance() : dateOfStart_;
      }
    }
    /**
     * <code>.LocalDateTime dateOfStart = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.LocalDateTime, dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder, dk.via.nbnp.databaseserver.protobuf.LocalDateTimeOrBuilder> 
        getDateOfStartFieldBuilder() {
      if (dateOfStartBuilder_ == null) {
        dateOfStartBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.nbnp.databaseserver.protobuf.LocalDateTime, dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder, dk.via.nbnp.databaseserver.protobuf.LocalDateTimeOrBuilder>(
                getDateOfStart(),
                getParentForChildren(),
                isClean());
        dateOfStart_ = null;
      }
      return dateOfStartBuilder_;
    }

    private java.util.List<dk.via.nbnp.databaseserver.protobuf.Message> messages_ =
      java.util.Collections.emptyList();
    private void ensureMessagesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        messages_ = new java.util.ArrayList<dk.via.nbnp.databaseserver.protobuf.Message>(messages_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.Message, dk.via.nbnp.databaseserver.protobuf.Message.Builder, dk.via.nbnp.databaseserver.protobuf.MessageOrBuilder> messagesBuilder_;

    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public java.util.List<dk.via.nbnp.databaseserver.protobuf.Message> getMessagesList() {
      if (messagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messages_);
      } else {
        return messagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public int getMessagesCount() {
      if (messagesBuilder_ == null) {
        return messages_.size();
      } else {
        return messagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.Message getMessages(int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);
      } else {
        return messagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public Builder setMessages(
        int index, dk.via.nbnp.databaseserver.protobuf.Message value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.set(index, value);
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public Builder setMessages(
        int index, dk.via.nbnp.databaseserver.protobuf.Message.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.set(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public Builder addMessages(dk.via.nbnp.databaseserver.protobuf.Message value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public Builder addMessages(
        int index, dk.via.nbnp.databaseserver.protobuf.Message value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(index, value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public Builder addMessages(
        dk.via.nbnp.databaseserver.protobuf.Message.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public Builder addMessages(
        int index, dk.via.nbnp.databaseserver.protobuf.Message.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public Builder addAllMessages(
        java.lang.Iterable<? extends dk.via.nbnp.databaseserver.protobuf.Message> values) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messages_);
        onChanged();
      } else {
        messagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public Builder clearMessages() {
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        messagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public Builder removeMessages(int index) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.remove(index);
        onChanged();
      } else {
        messagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.Message.Builder getMessagesBuilder(
        int index) {
      return getMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.MessageOrBuilder getMessagesOrBuilder(
        int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);  } else {
        return messagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public java.util.List<? extends dk.via.nbnp.databaseserver.protobuf.MessageOrBuilder> 
         getMessagesOrBuilderList() {
      if (messagesBuilder_ != null) {
        return messagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messages_);
      }
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.Message.Builder addMessagesBuilder() {
      return getMessagesFieldBuilder().addBuilder(
          dk.via.nbnp.databaseserver.protobuf.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.Message.Builder addMessagesBuilder(
        int index) {
      return getMessagesFieldBuilder().addBuilder(
          index, dk.via.nbnp.databaseserver.protobuf.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .Message messages = 6;</code>
     */
    public java.util.List<dk.via.nbnp.databaseserver.protobuf.Message.Builder> 
         getMessagesBuilderList() {
      return getMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.Message, dk.via.nbnp.databaseserver.protobuf.Message.Builder, dk.via.nbnp.databaseserver.protobuf.MessageOrBuilder> 
        getMessagesFieldBuilder() {
      if (messagesBuilder_ == null) {
        messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dk.via.nbnp.databaseserver.protobuf.Message, dk.via.nbnp.databaseserver.protobuf.Message.Builder, dk.via.nbnp.databaseserver.protobuf.MessageOrBuilder>(
                messages_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        messages_ = null;
      }
      return messagesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Conversation)
  }

  // @@protoc_insertion_point(class_scope:Conversation)
  private static final dk.via.nbnp.databaseserver.protobuf.Conversation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.nbnp.databaseserver.protobuf.Conversation();
  }

  public static dk.via.nbnp.databaseserver.protobuf.Conversation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Conversation>
      PARSER = new com.google.protobuf.AbstractParser<Conversation>() {
    @java.lang.Override
    public Conversation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Conversation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Conversation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Conversation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.Conversation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

