// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conversation.proto

package dk.via.nbnp.databaseserver.protobuf;

/**
 * Protobuf type {@code CreateConversationDTO}
 */
public final class CreateConversationDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreateConversationDTO)
    CreateConversationDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateConversationDTO.newBuilder() to construct.
  private CreateConversationDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateConversationDTO() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateConversationDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateConversationDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            sellerId_ = input.readInt64();
            break;
          }
          case 16: {

            buyerId_ = input.readInt64();
            break;
          }
          case 24: {

            itemId_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.nbnp.databaseserver.protobuf.ConversationOuterClass.internal_static_CreateConversationDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.nbnp.databaseserver.protobuf.ConversationOuterClass.internal_static_CreateConversationDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO.class, dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO.Builder.class);
  }

  public static final int SELLERID_FIELD_NUMBER = 1;
  private long sellerId_;
  /**
   * <code>int64 sellerId = 1;</code>
   * @return The sellerId.
   */
  @java.lang.Override
  public long getSellerId() {
    return sellerId_;
  }

  public static final int BUYERID_FIELD_NUMBER = 2;
  private long buyerId_;
  /**
   * <code>int64 buyerId = 2;</code>
   * @return The buyerId.
   */
  @java.lang.Override
  public long getBuyerId() {
    return buyerId_;
  }

  public static final int ITEMID_FIELD_NUMBER = 3;
  private long itemId_;
  /**
   * <code>int64 itemId = 3;</code>
   * @return The itemId.
   */
  @java.lang.Override
  public long getItemId() {
    return itemId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sellerId_ != 0L) {
      output.writeInt64(1, sellerId_);
    }
    if (buyerId_ != 0L) {
      output.writeInt64(2, buyerId_);
    }
    if (itemId_ != 0L) {
      output.writeInt64(3, itemId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sellerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, sellerId_);
    }
    if (buyerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, buyerId_);
    }
    if (itemId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, itemId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO)) {
      return super.equals(obj);
    }
    dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO other = (dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO) obj;

    if (getSellerId()
        != other.getSellerId()) return false;
    if (getBuyerId()
        != other.getBuyerId()) return false;
    if (getItemId()
        != other.getItemId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SELLERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSellerId());
    hash = (37 * hash) + BUYERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBuyerId());
    hash = (37 * hash) + ITEMID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getItemId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreateConversationDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreateConversationDTO)
      dk.via.nbnp.databaseserver.protobuf.CreateConversationDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.nbnp.databaseserver.protobuf.ConversationOuterClass.internal_static_CreateConversationDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.nbnp.databaseserver.protobuf.ConversationOuterClass.internal_static_CreateConversationDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO.class, dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO.Builder.class);
    }

    // Construct using dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sellerId_ = 0L;

      buyerId_ = 0L;

      itemId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.nbnp.databaseserver.protobuf.ConversationOuterClass.internal_static_CreateConversationDTO_descriptor;
    }

    @java.lang.Override
    public dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO getDefaultInstanceForType() {
      return dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO build() {
      dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO buildPartial() {
      dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO result = new dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO(this);
      result.sellerId_ = sellerId_;
      result.buyerId_ = buyerId_;
      result.itemId_ = itemId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO) {
        return mergeFrom((dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO other) {
      if (other == dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO.getDefaultInstance()) return this;
      if (other.getSellerId() != 0L) {
        setSellerId(other.getSellerId());
      }
      if (other.getBuyerId() != 0L) {
        setBuyerId(other.getBuyerId());
      }
      if (other.getItemId() != 0L) {
        setItemId(other.getItemId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long sellerId_ ;
    /**
     * <code>int64 sellerId = 1;</code>
     * @return The sellerId.
     */
    @java.lang.Override
    public long getSellerId() {
      return sellerId_;
    }
    /**
     * <code>int64 sellerId = 1;</code>
     * @param value The sellerId to set.
     * @return This builder for chaining.
     */
    public Builder setSellerId(long value) {
      
      sellerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sellerId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSellerId() {
      
      sellerId_ = 0L;
      onChanged();
      return this;
    }

    private long buyerId_ ;
    /**
     * <code>int64 buyerId = 2;</code>
     * @return The buyerId.
     */
    @java.lang.Override
    public long getBuyerId() {
      return buyerId_;
    }
    /**
     * <code>int64 buyerId = 2;</code>
     * @param value The buyerId to set.
     * @return This builder for chaining.
     */
    public Builder setBuyerId(long value) {
      
      buyerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 buyerId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuyerId() {
      
      buyerId_ = 0L;
      onChanged();
      return this;
    }

    private long itemId_ ;
    /**
     * <code>int64 itemId = 3;</code>
     * @return The itemId.
     */
    @java.lang.Override
    public long getItemId() {
      return itemId_;
    }
    /**
     * <code>int64 itemId = 3;</code>
     * @param value The itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemId(long value) {
      
      itemId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 itemId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemId() {
      
      itemId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CreateConversationDTO)
  }

  // @@protoc_insertion_point(class_scope:CreateConversationDTO)
  private static final dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO();
  }

  public static dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateConversationDTO>
      PARSER = new com.google.protobuf.AbstractParser<CreateConversationDTO>() {
    @java.lang.Override
    public CreateConversationDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateConversationDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateConversationDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateConversationDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.CreateConversationDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

