// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: item.proto

package dk.via.nbnp.databaseserver.protobuf;

public final class ItemOuterClass {
  private ItemOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateItemDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateItemDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateItemDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateItemDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchItemDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchItemDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetItemCount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetItemCount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nitem.proto\032\nuser.proto\032\016category.proto" +
      "\"\206\001\n\rCreateItemDTO\022\017\n\007ownerId\030\001 \001(\003\022\014\n\004n" +
      "ame\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\r\n\005price\030" +
      "\004 \001(\001\022\020\n\010currency\030\005 \001(\t\022\020\n\010category\030\006 \001(" +
      "\t\022\016\n\006status\030\007 \001(\010\"\222\001\n\rUpdateItemDTO\022\n\n\002i" +
      "d\030\001 \001(\003\022\017\n\007ownerId\030\002 \001(\003\022\014\n\004name\030\003 \001(\t\022\023" +
      "\n\013description\030\004 \001(\t\022\r\n\005price\030\005 \001(\001\022\020\n\010cu" +
      "rrency\030\006 \001(\t\022\020\n\010category\030\007 \001(\t\022\016\n\006status" +
      "\030\010 \001(\010\"\203\001\n\rSearchItemDTO\022\n\n\002id\030\001 \001(\003\022\017\n\007" +
      "ownerId\030\002 \001(\003\022\014\n\004name\030\003 \001(\t\022\023\n\013descripti" +
      "on\030\004 \001(\t\022\020\n\010minPrice\030\005 \001(\001\022\020\n\010maxPrice\030\006" +
      " \001(\001\022\016\n\006status\030\007 \001(\010\"\035\n\014GetItemCount\022\r\n\005" +
      "count\030\001 \001(\003\"\264\001\n\004Item\022\n\n\002id\030\001 \001(\003\022\024\n\005owne" +
      "r\030\002 \001(\0132\005.User\022\014\n\004name\030\003 \001(\t\022\023\n\013descript" +
      "ion\030\004 \001(\t\022\r\n\005price\030\005 \001(\001\022\020\n\010currency\030\006 \001" +
      "(\t\022$\n\014dateOfAdding\030\007 \001(\0132\016.LocalDateTime" +
      "\022\020\n\010category\030\010 \001(\t\022\016\n\006status\030\t \001(\0102\363\001\n\013I" +
      "temService\022#\n\ncreateItem\022\016.CreateItemDTO" +
      "\032\005.Item\022#\n\010getItems\022\016.SearchItemDTO\032\005.It" +
      "em0\001\022*\n\017getItemsByOwner\022\016.SearchItemDTO\032" +
      "\005.Item0\001\022$\n\013getItemById\022\016.SearchItemDTO\032" +
      "\005.Item\022#\n\nupdateItem\022\016.UpdateItemDTO\032\005.I" +
      "tem\022#\n\ndeleteItem\022\016.SearchItemDTO\032\005.Item" +
      "B\'\n#dk.via.nbnp.databaseserver.protobufP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          dk.via.nbnp.databaseserver.protobuf.UserOuterClass.getDescriptor(),
          dk.via.nbnp.databaseserver.protobuf.CategoryOuterClass.getDescriptor(),
        });
    internal_static_CreateItemDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateItemDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateItemDTO_descriptor,
        new java.lang.String[] { "OwnerId", "Name", "Description", "Price", "Currency", "Category", "Status", });
    internal_static_UpdateItemDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UpdateItemDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateItemDTO_descriptor,
        new java.lang.String[] { "Id", "OwnerId", "Name", "Description", "Price", "Currency", "Category", "Status", });
    internal_static_SearchItemDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SearchItemDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchItemDTO_descriptor,
        new java.lang.String[] { "Id", "OwnerId", "Name", "Description", "MinPrice", "MaxPrice", "Status", });
    internal_static_GetItemCount_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetItemCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetItemCount_descriptor,
        new java.lang.String[] { "Count", });
    internal_static_Item_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Item_descriptor,
        new java.lang.String[] { "Id", "Owner", "Name", "Description", "Price", "Currency", "DateOfAdding", "Category", "Status", });
    dk.via.nbnp.databaseserver.protobuf.UserOuterClass.getDescriptor();
    dk.via.nbnp.databaseserver.protobuf.CategoryOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
