// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package dk.via.nbnp.databaseserver.protobuf;

/**
 * Protobuf type {@code Notification}
 */
public final class Notification extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Notification)
    NotificationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Notification.newBuilder() to construct.
  private Notification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Notification() {
    message_ = "";
    title_ = "";
    notificationType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Notification();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Notification(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 16: {

            ownerId_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            notificationType_ = s;
            break;
          }
          case 48: {

            notificationTypeId_ = input.readInt64();
            break;
          }
          case 58: {
            dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder subBuilder = null;
            if (dateSent_ != null) {
              subBuilder = dateSent_.toBuilder();
            }
            dateSent_ = input.readMessage(dk.via.nbnp.databaseserver.protobuf.LocalDateTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateSent_);
              dateSent_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.nbnp.databaseserver.protobuf.NotificationOuterClass.internal_static_Notification_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.nbnp.databaseserver.protobuf.NotificationOuterClass.internal_static_Notification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.nbnp.databaseserver.protobuf.Notification.class, dk.via.nbnp.databaseserver.protobuf.Notification.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int OWNERID_FIELD_NUMBER = 2;
  private long ownerId_;
  /**
   * <code>int64 ownerId = 2;</code>
   * @return The ownerId.
   */
  @java.lang.Override
  public long getOwnerId() {
    return ownerId_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 4;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 4;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 4;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATESENT_FIELD_NUMBER = 7;
  private dk.via.nbnp.databaseserver.protobuf.LocalDateTime dateSent_;
  /**
   * <code>.LocalDateTime dateSent = 7;</code>
   * @return Whether the dateSent field is set.
   */
  @java.lang.Override
  public boolean hasDateSent() {
    return dateSent_ != null;
  }
  /**
   * <code>.LocalDateTime dateSent = 7;</code>
   * @return The dateSent.
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.LocalDateTime getDateSent() {
    return dateSent_ == null ? dk.via.nbnp.databaseserver.protobuf.LocalDateTime.getDefaultInstance() : dateSent_;
  }
  /**
   * <code>.LocalDateTime dateSent = 7;</code>
   */
  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.LocalDateTimeOrBuilder getDateSentOrBuilder() {
    return getDateSent();
  }

  public static final int NOTIFICATIONTYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object notificationType_;
  /**
   * <code>string notificationType = 5;</code>
   * @return The notificationType.
   */
  @java.lang.Override
  public java.lang.String getNotificationType() {
    java.lang.Object ref = notificationType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notificationType_ = s;
      return s;
    }
  }
  /**
   * <code>string notificationType = 5;</code>
   * @return The bytes for notificationType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNotificationTypeBytes() {
    java.lang.Object ref = notificationType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notificationType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTIFICATIONTYPEID_FIELD_NUMBER = 6;
  private long notificationTypeId_;
  /**
   * <code>int64 notificationTypeId = 6;</code>
   * @return The notificationTypeId.
   */
  @java.lang.Override
  public long getNotificationTypeId() {
    return notificationTypeId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (ownerId_ != 0L) {
      output.writeInt64(2, ownerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(notificationType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, notificationType_);
    }
    if (notificationTypeId_ != 0L) {
      output.writeInt64(6, notificationTypeId_);
    }
    if (dateSent_ != null) {
      output.writeMessage(7, getDateSent());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (ownerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, ownerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(notificationType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, notificationType_);
    }
    if (notificationTypeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, notificationTypeId_);
    }
    if (dateSent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getDateSent());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.nbnp.databaseserver.protobuf.Notification)) {
      return super.equals(obj);
    }
    dk.via.nbnp.databaseserver.protobuf.Notification other = (dk.via.nbnp.databaseserver.protobuf.Notification) obj;

    if (getId()
        != other.getId()) return false;
    if (getOwnerId()
        != other.getOwnerId()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (hasDateSent() != other.hasDateSent()) return false;
    if (hasDateSent()) {
      if (!getDateSent()
          .equals(other.getDateSent())) return false;
    }
    if (!getNotificationType()
        .equals(other.getNotificationType())) return false;
    if (getNotificationTypeId()
        != other.getNotificationTypeId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + OWNERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOwnerId());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    if (hasDateSent()) {
      hash = (37 * hash) + DATESENT_FIELD_NUMBER;
      hash = (53 * hash) + getDateSent().hashCode();
    }
    hash = (37 * hash) + NOTIFICATIONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getNotificationType().hashCode();
    hash = (37 * hash) + NOTIFICATIONTYPEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNotificationTypeId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.nbnp.databaseserver.protobuf.Notification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Notification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Notification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Notification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Notification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Notification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Notification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Notification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Notification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Notification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Notification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.nbnp.databaseserver.protobuf.Notification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.nbnp.databaseserver.protobuf.Notification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Notification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Notification)
      dk.via.nbnp.databaseserver.protobuf.NotificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.nbnp.databaseserver.protobuf.NotificationOuterClass.internal_static_Notification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.nbnp.databaseserver.protobuf.NotificationOuterClass.internal_static_Notification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.nbnp.databaseserver.protobuf.Notification.class, dk.via.nbnp.databaseserver.protobuf.Notification.Builder.class);
    }

    // Construct using dk.via.nbnp.databaseserver.protobuf.Notification.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      ownerId_ = 0L;

      message_ = "";

      title_ = "";

      if (dateSentBuilder_ == null) {
        dateSent_ = null;
      } else {
        dateSent_ = null;
        dateSentBuilder_ = null;
      }
      notificationType_ = "";

      notificationTypeId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.nbnp.databaseserver.protobuf.NotificationOuterClass.internal_static_Notification_descriptor;
    }

    @java.lang.Override
    public dk.via.nbnp.databaseserver.protobuf.Notification getDefaultInstanceForType() {
      return dk.via.nbnp.databaseserver.protobuf.Notification.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.nbnp.databaseserver.protobuf.Notification build() {
      dk.via.nbnp.databaseserver.protobuf.Notification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.nbnp.databaseserver.protobuf.Notification buildPartial() {
      dk.via.nbnp.databaseserver.protobuf.Notification result = new dk.via.nbnp.databaseserver.protobuf.Notification(this);
      result.id_ = id_;
      result.ownerId_ = ownerId_;
      result.message_ = message_;
      result.title_ = title_;
      if (dateSentBuilder_ == null) {
        result.dateSent_ = dateSent_;
      } else {
        result.dateSent_ = dateSentBuilder_.build();
      }
      result.notificationType_ = notificationType_;
      result.notificationTypeId_ = notificationTypeId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.nbnp.databaseserver.protobuf.Notification) {
        return mergeFrom((dk.via.nbnp.databaseserver.protobuf.Notification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.nbnp.databaseserver.protobuf.Notification other) {
      if (other == dk.via.nbnp.databaseserver.protobuf.Notification.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getOwnerId() != 0L) {
        setOwnerId(other.getOwnerId());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (other.hasDateSent()) {
        mergeDateSent(other.getDateSent());
      }
      if (!other.getNotificationType().isEmpty()) {
        notificationType_ = other.notificationType_;
        onChanged();
      }
      if (other.getNotificationTypeId() != 0L) {
        setNotificationTypeId(other.getNotificationTypeId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.nbnp.databaseserver.protobuf.Notification parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.nbnp.databaseserver.protobuf.Notification) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private long ownerId_ ;
    /**
     * <code>int64 ownerId = 2;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public long getOwnerId() {
      return ownerId_;
    }
    /**
     * <code>int64 ownerId = 2;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(long value) {
      
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ownerId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      
      ownerId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 4;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 4;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 4;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 4;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private dk.via.nbnp.databaseserver.protobuf.LocalDateTime dateSent_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.LocalDateTime, dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder, dk.via.nbnp.databaseserver.protobuf.LocalDateTimeOrBuilder> dateSentBuilder_;
    /**
     * <code>.LocalDateTime dateSent = 7;</code>
     * @return Whether the dateSent field is set.
     */
    public boolean hasDateSent() {
      return dateSentBuilder_ != null || dateSent_ != null;
    }
    /**
     * <code>.LocalDateTime dateSent = 7;</code>
     * @return The dateSent.
     */
    public dk.via.nbnp.databaseserver.protobuf.LocalDateTime getDateSent() {
      if (dateSentBuilder_ == null) {
        return dateSent_ == null ? dk.via.nbnp.databaseserver.protobuf.LocalDateTime.getDefaultInstance() : dateSent_;
      } else {
        return dateSentBuilder_.getMessage();
      }
    }
    /**
     * <code>.LocalDateTime dateSent = 7;</code>
     */
    public Builder setDateSent(dk.via.nbnp.databaseserver.protobuf.LocalDateTime value) {
      if (dateSentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateSent_ = value;
        onChanged();
      } else {
        dateSentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.LocalDateTime dateSent = 7;</code>
     */
    public Builder setDateSent(
        dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder builderForValue) {
      if (dateSentBuilder_ == null) {
        dateSent_ = builderForValue.build();
        onChanged();
      } else {
        dateSentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.LocalDateTime dateSent = 7;</code>
     */
    public Builder mergeDateSent(dk.via.nbnp.databaseserver.protobuf.LocalDateTime value) {
      if (dateSentBuilder_ == null) {
        if (dateSent_ != null) {
          dateSent_ =
            dk.via.nbnp.databaseserver.protobuf.LocalDateTime.newBuilder(dateSent_).mergeFrom(value).buildPartial();
        } else {
          dateSent_ = value;
        }
        onChanged();
      } else {
        dateSentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.LocalDateTime dateSent = 7;</code>
     */
    public Builder clearDateSent() {
      if (dateSentBuilder_ == null) {
        dateSent_ = null;
        onChanged();
      } else {
        dateSent_ = null;
        dateSentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.LocalDateTime dateSent = 7;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder getDateSentBuilder() {
      
      onChanged();
      return getDateSentFieldBuilder().getBuilder();
    }
    /**
     * <code>.LocalDateTime dateSent = 7;</code>
     */
    public dk.via.nbnp.databaseserver.protobuf.LocalDateTimeOrBuilder getDateSentOrBuilder() {
      if (dateSentBuilder_ != null) {
        return dateSentBuilder_.getMessageOrBuilder();
      } else {
        return dateSent_ == null ?
            dk.via.nbnp.databaseserver.protobuf.LocalDateTime.getDefaultInstance() : dateSent_;
      }
    }
    /**
     * <code>.LocalDateTime dateSent = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.nbnp.databaseserver.protobuf.LocalDateTime, dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder, dk.via.nbnp.databaseserver.protobuf.LocalDateTimeOrBuilder> 
        getDateSentFieldBuilder() {
      if (dateSentBuilder_ == null) {
        dateSentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.nbnp.databaseserver.protobuf.LocalDateTime, dk.via.nbnp.databaseserver.protobuf.LocalDateTime.Builder, dk.via.nbnp.databaseserver.protobuf.LocalDateTimeOrBuilder>(
                getDateSent(),
                getParentForChildren(),
                isClean());
        dateSent_ = null;
      }
      return dateSentBuilder_;
    }

    private java.lang.Object notificationType_ = "";
    /**
     * <code>string notificationType = 5;</code>
     * @return The notificationType.
     */
    public java.lang.String getNotificationType() {
      java.lang.Object ref = notificationType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notificationType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string notificationType = 5;</code>
     * @return The bytes for notificationType.
     */
    public com.google.protobuf.ByteString
        getNotificationTypeBytes() {
      java.lang.Object ref = notificationType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notificationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string notificationType = 5;</code>
     * @param value The notificationType to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notificationType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string notificationType = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNotificationType() {
      
      notificationType_ = getDefaultInstance().getNotificationType();
      onChanged();
      return this;
    }
    /**
     * <code>string notificationType = 5;</code>
     * @param value The bytes for notificationType to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notificationType_ = value;
      onChanged();
      return this;
    }

    private long notificationTypeId_ ;
    /**
     * <code>int64 notificationTypeId = 6;</code>
     * @return The notificationTypeId.
     */
    @java.lang.Override
    public long getNotificationTypeId() {
      return notificationTypeId_;
    }
    /**
     * <code>int64 notificationTypeId = 6;</code>
     * @param value The notificationTypeId to set.
     * @return This builder for chaining.
     */
    public Builder setNotificationTypeId(long value) {
      
      notificationTypeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 notificationTypeId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNotificationTypeId() {
      
      notificationTypeId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Notification)
  }

  // @@protoc_insertion_point(class_scope:Notification)
  private static final dk.via.nbnp.databaseserver.protobuf.Notification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.nbnp.databaseserver.protobuf.Notification();
  }

  public static dk.via.nbnp.databaseserver.protobuf.Notification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Notification>
      PARSER = new com.google.protobuf.AbstractParser<Notification>() {
    @java.lang.Override
    public Notification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Notification(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Notification> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Notification> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.nbnp.databaseserver.protobuf.Notification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

