// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image.proto

package dk.via.nbnp.databaseserver.protobuf;

public interface SearchImageDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchImageDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int64 itemId = 2;</code>
   * @return The itemId.
   */
  long getItemId();
}
