// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package via.sdj3.slaughterhouse.protobuf;

public interface TrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Tray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 trayId = 1;</code>
   * @return The trayId.
   */
  int getTrayId();

  /**
   * <code>string typeOfPart = 2;</code>
   * @return The typeOfPart.
   */
  java.lang.String getTypeOfPart();
  /**
   * <code>string typeOfPart = 2;</code>
   * @return The bytes for typeOfPart.
   */
  com.google.protobuf.ByteString
      getTypeOfPartBytes();

  /**
   * <code>double maxCapacity = 3;</code>
   * @return The maxCapacity.
   */
  double getMaxCapacity();
}
