// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaughterHouse.proto

package via.sdj3.slaughterhouse.protobuf;

/**
 * Protobuf type {@code Tray}
 */
public final class Tray extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Tray)
    TrayOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Tray.newBuilder() to construct.
  private Tray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Tray() {
    typeOfPart_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Tray();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Tray(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            trayId_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            typeOfPart_ = s;
            break;
          }
          case 25: {

            maxCapacity_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.slaughterhouse.protobuf.SlaughterHouseOuterClass.internal_static_Tray_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.slaughterhouse.protobuf.SlaughterHouseOuterClass.internal_static_Tray_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.slaughterhouse.protobuf.Tray.class, via.sdj3.slaughterhouse.protobuf.Tray.Builder.class);
  }

  public static final int TRAYID_FIELD_NUMBER = 1;
  private int trayId_;
  /**
   * <code>int32 trayId = 1;</code>
   * @return The trayId.
   */
  @java.lang.Override
  public int getTrayId() {
    return trayId_;
  }

  public static final int TYPEOFPART_FIELD_NUMBER = 2;
  private volatile java.lang.Object typeOfPart_;
  /**
   * <code>string typeOfPart = 2;</code>
   * @return The typeOfPart.
   */
  @java.lang.Override
  public java.lang.String getTypeOfPart() {
    java.lang.Object ref = typeOfPart_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeOfPart_ = s;
      return s;
    }
  }
  /**
   * <code>string typeOfPart = 2;</code>
   * @return The bytes for typeOfPart.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeOfPartBytes() {
    java.lang.Object ref = typeOfPart_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeOfPart_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAXCAPACITY_FIELD_NUMBER = 3;
  private double maxCapacity_;
  /**
   * <code>double maxCapacity = 3;</code>
   * @return The maxCapacity.
   */
  @java.lang.Override
  public double getMaxCapacity() {
    return maxCapacity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (trayId_ != 0) {
      output.writeInt32(1, trayId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(typeOfPart_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, typeOfPart_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxCapacity_) != 0) {
      output.writeDouble(3, maxCapacity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (trayId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, trayId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(typeOfPart_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, typeOfPart_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxCapacity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, maxCapacity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.slaughterhouse.protobuf.Tray)) {
      return super.equals(obj);
    }
    via.sdj3.slaughterhouse.protobuf.Tray other = (via.sdj3.slaughterhouse.protobuf.Tray) obj;

    if (getTrayId()
        != other.getTrayId()) return false;
    if (!getTypeOfPart()
        .equals(other.getTypeOfPart())) return false;
    if (java.lang.Double.doubleToLongBits(getMaxCapacity())
        != java.lang.Double.doubleToLongBits(
            other.getMaxCapacity())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRAYID_FIELD_NUMBER;
    hash = (53 * hash) + getTrayId();
    hash = (37 * hash) + TYPEOFPART_FIELD_NUMBER;
    hash = (53 * hash) + getTypeOfPart().hashCode();
    hash = (37 * hash) + MAXCAPACITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaxCapacity()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.slaughterhouse.protobuf.Tray parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhouse.protobuf.Tray parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhouse.protobuf.Tray parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhouse.protobuf.Tray parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhouse.protobuf.Tray parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhouse.protobuf.Tray parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhouse.protobuf.Tray parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhouse.protobuf.Tray parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaughterhouse.protobuf.Tray parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhouse.protobuf.Tray parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaughterhouse.protobuf.Tray parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhouse.protobuf.Tray parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.slaughterhouse.protobuf.Tray prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Tray}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Tray)
      via.sdj3.slaughterhouse.protobuf.TrayOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.slaughterhouse.protobuf.SlaughterHouseOuterClass.internal_static_Tray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.slaughterhouse.protobuf.SlaughterHouseOuterClass.internal_static_Tray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.slaughterhouse.protobuf.Tray.class, via.sdj3.slaughterhouse.protobuf.Tray.Builder.class);
    }

    // Construct using via.sdj3.slaughterhouse.protobuf.Tray.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      trayId_ = 0;

      typeOfPart_ = "";

      maxCapacity_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.slaughterhouse.protobuf.SlaughterHouseOuterClass.internal_static_Tray_descriptor;
    }

    @java.lang.Override
    public via.sdj3.slaughterhouse.protobuf.Tray getDefaultInstanceForType() {
      return via.sdj3.slaughterhouse.protobuf.Tray.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.slaughterhouse.protobuf.Tray build() {
      via.sdj3.slaughterhouse.protobuf.Tray result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.slaughterhouse.protobuf.Tray buildPartial() {
      via.sdj3.slaughterhouse.protobuf.Tray result = new via.sdj3.slaughterhouse.protobuf.Tray(this);
      result.trayId_ = trayId_;
      result.typeOfPart_ = typeOfPart_;
      result.maxCapacity_ = maxCapacity_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.slaughterhouse.protobuf.Tray) {
        return mergeFrom((via.sdj3.slaughterhouse.protobuf.Tray)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.slaughterhouse.protobuf.Tray other) {
      if (other == via.sdj3.slaughterhouse.protobuf.Tray.getDefaultInstance()) return this;
      if (other.getTrayId() != 0) {
        setTrayId(other.getTrayId());
      }
      if (!other.getTypeOfPart().isEmpty()) {
        typeOfPart_ = other.typeOfPart_;
        onChanged();
      }
      if (other.getMaxCapacity() != 0D) {
        setMaxCapacity(other.getMaxCapacity());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.slaughterhouse.protobuf.Tray parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.slaughterhouse.protobuf.Tray) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int trayId_ ;
    /**
     * <code>int32 trayId = 1;</code>
     * @return The trayId.
     */
    @java.lang.Override
    public int getTrayId() {
      return trayId_;
    }
    /**
     * <code>int32 trayId = 1;</code>
     * @param value The trayId to set.
     * @return This builder for chaining.
     */
    public Builder setTrayId(int value) {
      
      trayId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 trayId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrayId() {
      
      trayId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object typeOfPart_ = "";
    /**
     * <code>string typeOfPart = 2;</code>
     * @return The typeOfPart.
     */
    public java.lang.String getTypeOfPart() {
      java.lang.Object ref = typeOfPart_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeOfPart_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string typeOfPart = 2;</code>
     * @return The bytes for typeOfPart.
     */
    public com.google.protobuf.ByteString
        getTypeOfPartBytes() {
      java.lang.Object ref = typeOfPart_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeOfPart_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string typeOfPart = 2;</code>
     * @param value The typeOfPart to set.
     * @return This builder for chaining.
     */
    public Builder setTypeOfPart(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeOfPart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string typeOfPart = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeOfPart() {
      
      typeOfPart_ = getDefaultInstance().getTypeOfPart();
      onChanged();
      return this;
    }
    /**
     * <code>string typeOfPart = 2;</code>
     * @param value The bytes for typeOfPart to set.
     * @return This builder for chaining.
     */
    public Builder setTypeOfPartBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeOfPart_ = value;
      onChanged();
      return this;
    }

    private double maxCapacity_ ;
    /**
     * <code>double maxCapacity = 3;</code>
     * @return The maxCapacity.
     */
    @java.lang.Override
    public double getMaxCapacity() {
      return maxCapacity_;
    }
    /**
     * <code>double maxCapacity = 3;</code>
     * @param value The maxCapacity to set.
     * @return This builder for chaining.
     */
    public Builder setMaxCapacity(double value) {
      
      maxCapacity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double maxCapacity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxCapacity() {
      
      maxCapacity_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Tray)
  }

  // @@protoc_insertion_point(class_scope:Tray)
  private static final via.sdj3.slaughterhouse.protobuf.Tray DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.slaughterhouse.protobuf.Tray();
  }

  public static via.sdj3.slaughterhouse.protobuf.Tray getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Tray>
      PARSER = new com.google.protobuf.AbstractParser<Tray>() {
    @java.lang.Override
    public Tray parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Tray(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Tray> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Tray> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.slaughterhouse.protobuf.Tray getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

